# Location of the .bashrc file (this file will be reset and have things added to it)
BASHRC=$HOME/.bashrc

# General location of Apps
APPS_PATH=$HOME/Apps

# Defines Golang version to be installed
GO_VERSION=1.22.4

# IDEA Toolbox version to download
IDEA_TOOLBOX_VERSION=1.22.10970 

